/nologo
/optimize+
/debug-
/unsafe-
/warn:0
/out:c:/builds/mindpowered/logic/english-auction/build/vcs/csharp/bin/englishauction.dll
/target:library
/reference:c:/builds/mindpowered/logic/english-auction/build/vcs/csharp/bin/maglev.dll
src\EnumValue.cs
src\englishauction\BidRepository.cs
src\englishauction\EnglishAuction.cs
src\Type.cs
src\englishauction\BidModel.cs
src\englishauction\AuctionRepository.cs
src\englishauction\AuctionModel.cs
src\UInt.cs
src\mindpowered\englishauction\EnglishAuction.cs