// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository : global::haxe.lang.HxObject {
		
		static AuctionRepository() {
			unchecked{
				#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{3254785, 89092393, 770176554, 958206052, 1362300083, 1833056016, 1835582091}, new string[]{"Add", "FindAuctionsStarting", "Edit", "Remove", "FindOpenAuctions", "FindAuctionsEnding", "FindById"});
			}
		}
		#line default
		
		public AuctionRepository(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public AuctionRepository(global::maglev.MagLev bus) {
			#line 9 "/my-component/src/englishauction/AuctionRepository.hx"
			global::englishauction.AuctionRepository.__hx_ctor_englishauction_AuctionRepository(this, bus);
		}
		#line default
		
		protected static void __hx_ctor_englishauction_AuctionRepository(global::englishauction.AuctionRepository __hx_this, global::maglev.MagLev bus) {
			#line 10 "/my-component/src/englishauction/AuctionRepository.hx"
			__hx_this.bus = bus;
		}
		#line default
		
		public global::maglev.MagLev bus;
		
		public virtual void Add(global::englishauction.AuctionModel auction, global::haxe.lang.Function callback) {
			#line 14 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevObject obj = global::maglev.MagLevObject.create();
			obj.@set("start", global::maglev.MagLevNumber.fromInt(auction.start));
			#line 16 "/my-component/src/englishauction/AuctionRepository.hx"
			obj.@set("end", global::maglev.MagLevNumber.fromInt(auction.end));
			obj.@set("startingPrice", global::maglev.MagLevNumber.fromFloat(auction.startingPrice));
			#line 18 "/my-component/src/englishauction/AuctionRepository.hx"
			obj.@set("reservePrice", global::maglev.MagLevNumber.fromFloat(auction.reservePrice));
			obj.@set("priceIncrement", global::maglev.MagLevNumber.fromFloat(auction.priceIncrement));
			#line 20 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevArray args = global::maglev.MagLevArray.create();
			args.push(obj);
			#line 22 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevResult res = this.bus.call("Persistence.EnglishAuction.Auction.CreateNew", args);
			res.onResult(new global::englishauction.AuctionRepository_Add_23__Fun(callback));
			#line 27 "/my-component/src/englishauction/AuctionRepository.hx"
			res.onError(( (( global::englishauction.AuctionRepository_Add_27__Fun.__hx_current != null )) ? (global::englishauction.AuctionRepository_Add_27__Fun.__hx_current) : (global::englishauction.AuctionRepository_Add_27__Fun.__hx_current = ((global::englishauction.AuctionRepository_Add_27__Fun) (new global::englishauction.AuctionRepository_Add_27__Fun()) )) ));
		}
		#line default
		
		public virtual void Edit(global::englishauction.AuctionModel auction, global::haxe.lang.Function callback) {
		}
		
		
		public virtual void Remove(string auctionId, global::haxe.lang.Function callback) {
		}
		
		
		public virtual void FindById(string auctionId, global::haxe.lang.Function callback) {
			#line 41 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevArray args = global::maglev.MagLevArray.create();
			args.push(global::maglev.MagLevString.fromString(auctionId));
			#line 43 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevResult res = this.bus.call("Persistence.EnglishAuction.Auction.FindById", args);
			res.onError(( (( global::englishauction.AuctionRepository_FindById_44__Fun.__hx_current != null )) ? (global::englishauction.AuctionRepository_FindById_44__Fun.__hx_current) : (global::englishauction.AuctionRepository_FindById_44__Fun.__hx_current = ((global::englishauction.AuctionRepository_FindById_44__Fun) (new global::englishauction.AuctionRepository_FindById_44__Fun()) )) ));
			#line 47 "/my-component/src/englishauction/AuctionRepository.hx"
			res.onResult(new global::englishauction.AuctionRepository_FindById_47__Fun(res, callback));
		}
		#line default
		
		public virtual void FindAuctionsEnding(int endfrom, int endto, int page, int perpage, string sort, bool asc, global::haxe.lang.Function callback) {
			#line 65 "/my-component/src/englishauction/AuctionRepository.hx"
			global::Array<object> auctions = new global::Array<object>();
			global::maglev.MagLevArray args = global::maglev.MagLevArray.create();
			#line 67 "/my-component/src/englishauction/AuctionRepository.hx"
			args.push(global::maglev.MagLevNumber.fromInt(endfrom));
			args.push(global::maglev.MagLevNumber.fromInt(endto));
			#line 69 "/my-component/src/englishauction/AuctionRepository.hx"
			args.push(global::maglev.MagLevNumber.fromInt(page));
			args.push(global::maglev.MagLevNumber.fromInt(perpage));
			#line 71 "/my-component/src/englishauction/AuctionRepository.hx"
			args.push(global::maglev.MagLevString.fromString(sort));
			args.push(global::maglev.MagLevBoolean.fromBool(asc));
			#line 73 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevResult res = this.bus.call("Persistence.EnglishAuction.Auction.FindEnding", args);
			res.onError(( (( global::englishauction.AuctionRepository_FindAuctionsEnding_74__Fun.__hx_current != null )) ? (global::englishauction.AuctionRepository_FindAuctionsEnding_74__Fun.__hx_current) : (global::englishauction.AuctionRepository_FindAuctionsEnding_74__Fun.__hx_current = ((global::englishauction.AuctionRepository_FindAuctionsEnding_74__Fun) (new global::englishauction.AuctionRepository_FindAuctionsEnding_74__Fun()) )) ));
			#line 77 "/my-component/src/englishauction/AuctionRepository.hx"
			res.onResult(new global::englishauction.AuctionRepository_FindAuctionsEnding_77__Fun(callback, auctions));
		}
		#line default
		
		public virtual void FindAuctionsStarting(int startfrom, int startto, int page, int perpage, string sort, bool asc, global::haxe.lang.Function callback) {
			#line 99 "/my-component/src/englishauction/AuctionRepository.hx"
			global::Array<object> auctions = new global::Array<object>();
			global::maglev.MagLevArray args = global::maglev.MagLevArray.create();
			#line 101 "/my-component/src/englishauction/AuctionRepository.hx"
			args.push(global::maglev.MagLevNumber.fromInt(startfrom));
			args.push(global::maglev.MagLevNumber.fromInt(startto));
			#line 103 "/my-component/src/englishauction/AuctionRepository.hx"
			args.push(global::maglev.MagLevNumber.fromInt(page));
			args.push(global::maglev.MagLevNumber.fromInt(perpage));
			#line 105 "/my-component/src/englishauction/AuctionRepository.hx"
			args.push(global::maglev.MagLevString.fromString(sort));
			args.push(global::maglev.MagLevBoolean.fromBool(asc));
			#line 107 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevResult res = this.bus.call("Persistence.EnglishAuction.Auction.FindStarting", args);
			res.onError(( (( global::englishauction.AuctionRepository_FindAuctionsStarting_108__Fun.__hx_current != null )) ? (global::englishauction.AuctionRepository_FindAuctionsStarting_108__Fun.__hx_current) : (global::englishauction.AuctionRepository_FindAuctionsStarting_108__Fun.__hx_current = ((global::englishauction.AuctionRepository_FindAuctionsStarting_108__Fun) (new global::englishauction.AuctionRepository_FindAuctionsStarting_108__Fun()) )) ));
			#line 111 "/my-component/src/englishauction/AuctionRepository.hx"
			res.onResult(new global::englishauction.AuctionRepository_FindAuctionsStarting_111__Fun(res, callback, auctions));
		}
		#line default
		
		public virtual void FindOpenAuctions(int page, int perpage, string sort, bool asc, global::haxe.lang.Function callback) {
			#line 132 "/my-component/src/englishauction/AuctionRepository.hx"
			global::Array<object> auctions = new global::Array<object>();
			global::maglev.MagLevArray args = global::maglev.MagLevArray.create();
			#line 134 "/my-component/src/englishauction/AuctionRepository.hx"
			args.push(global::maglev.MagLevNumber.fromInt(page));
			args.push(global::maglev.MagLevNumber.fromInt(perpage));
			#line 136 "/my-component/src/englishauction/AuctionRepository.hx"
			args.push(global::maglev.MagLevString.fromString(sort));
			args.push(global::maglev.MagLevBoolean.fromBool(asc));
			#line 138 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevResult res = this.bus.call("Persistence.EnglishAuction.Auction.FindOpen", args);
			res.onError(( (( global::englishauction.AuctionRepository_FindOpenAuctions_139__Fun.__hx_current != null )) ? (global::englishauction.AuctionRepository_FindOpenAuctions_139__Fun.__hx_current) : (global::englishauction.AuctionRepository_FindOpenAuctions_139__Fun.__hx_current = ((global::englishauction.AuctionRepository_FindOpenAuctions_139__Fun) (new global::englishauction.AuctionRepository_FindOpenAuctions_139__Fun()) )) ));
			#line 142 "/my-component/src/englishauction/AuctionRepository.hx"
			res.onResult(new global::englishauction.AuctionRepository_FindOpenAuctions_142__Fun(res, callback, auctions));
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
				switch (hash) {
					case 4899648:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.bus = ((global::maglev.MagLev) (@value) );
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return @value;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
				switch (hash) {
					case 1362300083:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "FindOpenAuctions", 1362300083)) );
					}
					
					
					case 89092393:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "FindAuctionsStarting", 89092393)) );
					}
					
					
					case 1833056016:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "FindAuctionsEnding", 1833056016)) );
					}
					
					
					case 1835582091:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "FindById", 1835582091)) );
					}
					
					
					case 958206052:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Remove", 958206052)) );
					}
					
					
					case 770176554:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Edit", 770176554)) );
					}
					
					
					case 3254785:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Add", 3254785)) );
					}
					
					
					case 4899648:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return this.bus;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
				switch (hash) {
					case 1362300083:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.FindOpenAuctions(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[1])) ), global::haxe.lang.Runtime.toString(dynargs[2]), global::haxe.lang.Runtime.toBool(dynargs[3]), ((global::haxe.lang.Function) (dynargs[4]) ));
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						break;
					}
					
					
					case 89092393:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.FindAuctionsStarting(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[1])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[2])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[3])) ), global::haxe.lang.Runtime.toString(dynargs[4]), global::haxe.lang.Runtime.toBool(dynargs[5]), ((global::haxe.lang.Function) (dynargs[6]) ));
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						break;
					}
					
					
					case 1833056016:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.FindAuctionsEnding(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[1])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[2])) ), ((int) (global::haxe.lang.Runtime.toInt(dynargs[3])) ), global::haxe.lang.Runtime.toString(dynargs[4]), global::haxe.lang.Runtime.toBool(dynargs[5]), ((global::haxe.lang.Function) (dynargs[6]) ));
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						break;
					}
					
					
					case 1835582091:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.FindById(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						break;
					}
					
					
					case 958206052:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.Remove(global::haxe.lang.Runtime.toString(dynargs[0]), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						break;
					}
					
					
					case 770176554:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.Edit(((global::englishauction.AuctionModel) (dynargs[0]) ), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						break;
					}
					
					
					case 3254785:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.Add(((global::englishauction.AuctionModel) (dynargs[0]) ), ((global::haxe.lang.Function) (dynargs[1]) ));
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						break;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
			baseArr.push("bus");
			#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository_Add_23__Fun : global::haxe.lang.Function {
		
		public AuctionRepository_Add_23__Fun(global::haxe.lang.Function callback) : base(1, 0) {
			#line 23 "/my-component/src/englishauction/AuctionRepository.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 23 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevAny ret = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			this.callback.__hx_invoke1_o(default(double), (((global::maglev.MagLevString) (ret) )).getString());
			#line 25 "/my-component/src/englishauction/AuctionRepository.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository_Add_27__Fun : global::haxe.lang.Function {
		
		public AuctionRepository_Add_27__Fun() : base(1, 0) {
		}
		
		
		public static global::englishauction.AuctionRepository_Add_27__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 27 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevError err = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(err.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository_FindById_44__Fun : global::haxe.lang.Function {
		
		public AuctionRepository_FindById_44__Fun() : base(1, 0) {
		}
		
		
		public static global::englishauction.AuctionRepository_FindById_44__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 44 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevError err = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(err.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository_FindById_47__Fun : global::haxe.lang.Function {
		
		public AuctionRepository_FindById_47__Fun(global::maglev.MagLevResult res, global::haxe.lang.Function callback) : base(1, 0) {
			#line 47 "/my-component/src/englishauction/AuctionRepository.hx"
			this.res = res;
			#line 47 "/my-component/src/englishauction/AuctionRepository.hx"
			this.callback = callback;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 47 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevAny ret = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			if (global::Std.isOfType(((object) (this.res.getResult()) ), ((object) (typeof(global::maglev.MagLevNull)) ))) {
				#line 49 "/my-component/src/englishauction/AuctionRepository.hx"
				this.callback.__hx_invoke1_o(default(double), null);
			}
			
			#line 51 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevObject resobj = ((global::maglev.MagLevObject) (this.res.getResult()) );
			global::englishauction.AuctionModel model = new global::englishauction.AuctionModel();
			#line 53 "/my-component/src/englishauction/AuctionRepository.hx"
			model.id = (((global::maglev.MagLevString) (resobj.@get("auctionId")) )).getString();
			model.start = (((global::maglev.MagLevNumber) (resobj.@get("start")) )).getInt();
			#line 55 "/my-component/src/englishauction/AuctionRepository.hx"
			model.end = (((global::maglev.MagLevNumber) (resobj.@get("end")) )).getInt();
			model.startingPrice = (((global::maglev.MagLevNumber) (resobj.@get("startingPrice")) )).getFloat();
			#line 57 "/my-component/src/englishauction/AuctionRepository.hx"
			model.reservePrice = (((global::maglev.MagLevNumber) (resobj.@get("reservePrice")) )).getFloat();
			model.priceIncrement = (((global::maglev.MagLevNumber) (resobj.@get("priceIncrement")) )).getFloat();
			#line 59 "/my-component/src/englishauction/AuctionRepository.hx"
			this.callback.__hx_invoke1_o(default(double), model);
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::maglev.MagLevResult res;
		
		public global::haxe.lang.Function callback;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository_FindAuctionsEnding_74__Fun : global::haxe.lang.Function {
		
		public AuctionRepository_FindAuctionsEnding_74__Fun() : base(1, 0) {
		}
		
		
		public static global::englishauction.AuctionRepository_FindAuctionsEnding_74__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 74 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevError err = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(err.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository_FindAuctionsEnding_77__Fun : global::haxe.lang.Function {
		
		public AuctionRepository_FindAuctionsEnding_77__Fun(global::haxe.lang.Function callback, global::Array<object> auctions) : base(1, 0) {
			#line 77 "/my-component/src/englishauction/AuctionRepository.hx"
			this.callback = callback;
			#line 77 "/my-component/src/englishauction/AuctionRepository.hx"
			this.auctions = auctions;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 77 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevAny ret = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			global::maglev.MagLevArray arr = ((global::maglev.MagLevArray) (ret) );
			#line 79 "/my-component/src/englishauction/AuctionRepository.hx"
			int i = 0;
			while (( i < arr.size() )) {
				#line 81 "/my-component/src/englishauction/AuctionRepository.hx"
				global::englishauction.AuctionModel model = new global::englishauction.AuctionModel();
				global::maglev.MagLevObject resobj = ((global::maglev.MagLevObject) (arr.@get(i)) );
				#line 83 "/my-component/src/englishauction/AuctionRepository.hx"
				model.id = (((global::maglev.MagLevString) (resobj.@get("auctionId")) )).getString();
				model.start = (((global::maglev.MagLevNumber) (resobj.@get("start")) )).getInt();
				#line 85 "/my-component/src/englishauction/AuctionRepository.hx"
				model.end = (((global::maglev.MagLevNumber) (resobj.@get("end")) )).getInt();
				model.startingPrice = (((global::maglev.MagLevNumber) (resobj.@get("startingPrice")) )).getFloat();
				#line 87 "/my-component/src/englishauction/AuctionRepository.hx"
				model.reservePrice = (((global::maglev.MagLevNumber) (resobj.@get("reservePrice")) )).getFloat();
				model.priceIncrement = (((global::maglev.MagLevNumber) (resobj.@get("priceIncrement")) )).getFloat();
				#line 89 "/my-component/src/englishauction/AuctionRepository.hx"
				this.auctions.push(model);
				 ++ i;
			}
			
			#line 92 "/my-component/src/englishauction/AuctionRepository.hx"
			this.callback.__hx_invoke1_o(default(double), this.auctions);
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::haxe.lang.Function callback;
		
		public global::Array<object> auctions;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository_FindAuctionsStarting_108__Fun : global::haxe.lang.Function {
		
		public AuctionRepository_FindAuctionsStarting_108__Fun() : base(1, 0) {
		}
		
		
		public static global::englishauction.AuctionRepository_FindAuctionsStarting_108__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 108 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevError err = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(err.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository_FindAuctionsStarting_111__Fun : global::haxe.lang.Function {
		
		public AuctionRepository_FindAuctionsStarting_111__Fun(global::maglev.MagLevResult res, global::haxe.lang.Function callback, global::Array<object> auctions) : base(1, 0) {
			#line 111 "/my-component/src/englishauction/AuctionRepository.hx"
			this.res = res;
			#line 111 "/my-component/src/englishauction/AuctionRepository.hx"
			this.callback = callback;
			#line 111 "/my-component/src/englishauction/AuctionRepository.hx"
			this.auctions = auctions;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 111 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevAny ret = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			global::maglev.MagLevArray arr = ((global::maglev.MagLevArray) (this.res.getResult()) );
			#line 113 "/my-component/src/englishauction/AuctionRepository.hx"
			int i = 0;
			while (( i < arr.size() )) {
				#line 115 "/my-component/src/englishauction/AuctionRepository.hx"
				global::englishauction.AuctionModel model = new global::englishauction.AuctionModel();
				global::maglev.MagLevObject resobj = ((global::maglev.MagLevObject) (arr.@get(i)) );
				#line 117 "/my-component/src/englishauction/AuctionRepository.hx"
				model.id = (((global::maglev.MagLevString) (resobj.@get("auctionId")) )).getString();
				model.start = (((global::maglev.MagLevNumber) (resobj.@get("start")) )).getInt();
				#line 119 "/my-component/src/englishauction/AuctionRepository.hx"
				model.end = (((global::maglev.MagLevNumber) (resobj.@get("end")) )).getInt();
				model.startingPrice = (((global::maglev.MagLevNumber) (resobj.@get("startingPrice")) )).getFloat();
				#line 121 "/my-component/src/englishauction/AuctionRepository.hx"
				model.reservePrice = (((global::maglev.MagLevNumber) (resobj.@get("reservePrice")) )).getFloat();
				model.priceIncrement = (((global::maglev.MagLevNumber) (resobj.@get("priceIncrement")) )).getFloat();
				#line 123 "/my-component/src/englishauction/AuctionRepository.hx"
				this.auctions.push(model);
				 ++ i;
			}
			
			#line 126 "/my-component/src/englishauction/AuctionRepository.hx"
			this.callback.__hx_invoke1_o(default(double), this.auctions);
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::maglev.MagLevResult res;
		
		public global::haxe.lang.Function callback;
		
		public global::Array<object> auctions;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository_FindOpenAuctions_139__Fun : global::haxe.lang.Function {
		
		public AuctionRepository_FindOpenAuctions_139__Fun() : base(1, 0) {
		}
		
		
		public static global::englishauction.AuctionRepository_FindOpenAuctions_139__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 139 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevError err = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevError) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevError) (__fn_dyn1) )) );
			throw ((global::System.Exception) (global::haxe.Exception.thrown(err.getMessage())) );
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository_FindOpenAuctions_142__Fun : global::haxe.lang.Function {
		
		public AuctionRepository_FindOpenAuctions_142__Fun(global::maglev.MagLevResult res, global::haxe.lang.Function callback, global::Array<object> auctions) : base(1, 0) {
			#line 142 "/my-component/src/englishauction/AuctionRepository.hx"
			this.res = res;
			#line 142 "/my-component/src/englishauction/AuctionRepository.hx"
			this.callback = callback;
			#line 142 "/my-component/src/englishauction/AuctionRepository.hx"
			this.auctions = auctions;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 142 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevAny ret = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevAny) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevAny) (__fn_dyn1) )) );
			global::maglev.MagLevArray arr = ((global::maglev.MagLevArray) (this.res.getResult()) );
			#line 144 "/my-component/src/englishauction/AuctionRepository.hx"
			int i = 0;
			while (( i < arr.size() )) {
				#line 146 "/my-component/src/englishauction/AuctionRepository.hx"
				global::englishauction.AuctionModel model = new global::englishauction.AuctionModel();
				global::maglev.MagLevObject resobj = ((global::maglev.MagLevObject) (arr.@get(i)) );
				#line 148 "/my-component/src/englishauction/AuctionRepository.hx"
				model.id = (((global::maglev.MagLevString) (resobj.@get("auctionId")) )).getString();
				model.start = (((global::maglev.MagLevNumber) (resobj.@get("start")) )).getInt();
				#line 150 "/my-component/src/englishauction/AuctionRepository.hx"
				model.end = (((global::maglev.MagLevNumber) (resobj.@get("end")) )).getInt();
				model.startingPrice = (((global::maglev.MagLevNumber) (resobj.@get("startingPrice")) )).getFloat();
				#line 152 "/my-component/src/englishauction/AuctionRepository.hx"
				model.reservePrice = (((global::maglev.MagLevNumber) (resobj.@get("reservePrice")) )).getFloat();
				model.priceIncrement = (((global::maglev.MagLevNumber) (resobj.@get("priceIncrement")) )).getFloat();
				#line 154 "/my-component/src/englishauction/AuctionRepository.hx"
				this.auctions.push(model);
				 ++ i;
			}
			
			#line 157 "/my-component/src/englishauction/AuctionRepository.hx"
			this.callback.__hx_invoke1_o(default(double), this.auctions);
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
		public global::maglev.MagLevResult res;
		
		public global::haxe.lang.Function callback;
		
		public global::Array<object> auctions;
		
	}
}


