// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionModel : global::haxe.lang.HxObject {
		
		public AuctionModel(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public AuctionModel() {
			#line 5 "/my-component/src/englishauction/AuctionModel.hx"
			global::englishauction.AuctionModel.__hx_ctor_englishauction_AuctionModel(this);
		}
		#line default
		
		protected static void __hx_ctor_englishauction_AuctionModel(global::englishauction.AuctionModel __hx_this) {
		}
		
		
		public string id;
		
		public int start;
		
		public int end;
		
		public double startingPrice;
		
		public double reservePrice;
		
		public double priceIncrement;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/englishauction/AuctionModel.hx"
				switch (hash) {
					case 977731174:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.priceIncrement = ((double) (@value) );
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					case 449914541:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.reservePrice = ((double) (@value) );
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					case 158229673:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.startingPrice = ((double) (@value) );
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					case 5047259:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.end = ((int) (@value) );
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					case 67859554:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.start = ((int) (@value) );
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/englishauction/AuctionModel.hx"
				switch (hash) {
					case 977731174:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.priceIncrement = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					case 449914541:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.reservePrice = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					case 158229673:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.startingPrice = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					case 5047259:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.end = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					case 67859554:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.start = ((int) (global::haxe.lang.Runtime.toInt(@value)) );
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					case 23515:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						this.id = global::haxe.lang.Runtime.toString(@value);
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return @value;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/englishauction/AuctionModel.hx"
				switch (hash) {
					case 977731174:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return this.priceIncrement;
					}
					
					
					case 449914541:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return this.reservePrice;
					}
					
					
					case 158229673:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return this.startingPrice;
					}
					
					
					case 5047259:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return this.end;
					}
					
					
					case 67859554:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return this.start;
					}
					
					
					case 23515:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return this.id;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/englishauction/AuctionModel.hx"
				switch (hash) {
					case 977731174:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return this.priceIncrement;
					}
					
					
					case 449914541:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return this.reservePrice;
					}
					
					
					case 158229673:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return this.startingPrice;
					}
					
					
					case 5047259:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return ((double) (this.end) );
					}
					
					
					case 67859554:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return ((double) (this.start) );
					}
					
					
					default:
					{
						#line 3 "/my-component/src/englishauction/AuctionModel.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 3 "/my-component/src/englishauction/AuctionModel.hx"
			baseArr.push("priceIncrement");
			#line 3 "/my-component/src/englishauction/AuctionModel.hx"
			baseArr.push("reservePrice");
			#line 3 "/my-component/src/englishauction/AuctionModel.hx"
			baseArr.push("startingPrice");
			#line 3 "/my-component/src/englishauction/AuctionModel.hx"
			baseArr.push("end");
			#line 3 "/my-component/src/englishauction/AuctionModel.hx"
			baseArr.push("start");
			#line 3 "/my-component/src/englishauction/AuctionModel.hx"
			baseArr.push("id");
			#line 3 "/my-component/src/englishauction/AuctionModel.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


