// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class AuctionRepository : global::haxe.lang.HxObject {
		
		static AuctionRepository() {
			unchecked{
				#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{3254785, 770176554, 958206052, 1835582091}, new string[]{"Add", "Edit", "Remove", "FindById"});
			}
		}
		#line default
		
		public AuctionRepository(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public AuctionRepository(global::maglev.MagLev bus) {
			#line 9 "/my-component/src/englishauction/AuctionRepository.hx"
			global::englishauction.AuctionRepository.__hx_ctor_englishauction_AuctionRepository(this, bus);
		}
		#line default
		
		protected static void __hx_ctor_englishauction_AuctionRepository(global::englishauction.AuctionRepository __hx_this, global::maglev.MagLev bus) {
			#line 10 "/my-component/src/englishauction/AuctionRepository.hx"
			__hx_this.bus = bus;
		}
		#line default
		
		public global::maglev.MagLev bus;
		
		public virtual void Add(global::englishauction.AuctionModel auction) {
		}
		
		
		public virtual void Edit(global::englishauction.AuctionModel auction) {
		}
		
		
		public virtual void Remove(string auctionId) {
		}
		
		
		public virtual global::englishauction.AuctionModel FindById(string auctionId) {
			#line 26 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevArray myargs = global::maglev.MagLevArray.create();
			myargs.push(global::maglev.MagLevString.fromString("EnglishAuction.Auction"));
			#line 28 "/my-component/src/englishauction/AuctionRepository.hx"
			myargs.push(global::maglev.MagLevString.fromString("FindById"));
			myargs.push(global::maglev.MagLevString.fromString(auctionId));
			#line 30 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevResult res = this.bus.call("Persistence.Get", myargs);
			if (res.isError()) {
				#line 32 "/my-component/src/englishauction/AuctionRepository.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown(res.getError().getMessage())) );
			}
			
			#line 34 "/my-component/src/englishauction/AuctionRepository.hx"
			if (global::Std.isOfType(((object) (res.getResult()) ), ((object) (typeof(global::maglev.MagLevNull)) ))) {
				#line 35 "/my-component/src/englishauction/AuctionRepository.hx"
				return null;
			}
			
			#line 37 "/my-component/src/englishauction/AuctionRepository.hx"
			global::maglev.MagLevObject resobj = ((global::maglev.MagLevObject) (res.getResult()) );
			global::englishauction.AuctionModel model = new global::englishauction.AuctionModel();
			#line 39 "/my-component/src/englishauction/AuctionRepository.hx"
			model.id = (((global::maglev.MagLevString) (resobj.@get("auctionId")) )).getString();
			model.start = (((global::maglev.MagLevNumber) (resobj.@get("start")) )).getInt();
			#line 41 "/my-component/src/englishauction/AuctionRepository.hx"
			model.end = (((global::maglev.MagLevNumber) (resobj.@get("end")) )).getInt();
			model.startingPrice = (((global::maglev.MagLevNumber) (resobj.@get("startingPrice")) )).getFloat();
			#line 43 "/my-component/src/englishauction/AuctionRepository.hx"
			model.reservePrice = (((global::maglev.MagLevNumber) (resobj.@get("reservePrice")) )).getFloat();
			model.priceIncrement = (((global::maglev.MagLevNumber) (resobj.@get("priceIncrement")) )).getFloat();
			#line 45 "/my-component/src/englishauction/AuctionRepository.hx"
			return model;
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
				switch (hash) {
					case 4899648:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.bus = ((global::maglev.MagLev) (@value) );
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return @value;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
				switch (hash) {
					case 1835582091:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "FindById", 1835582091)) );
					}
					
					
					case 958206052:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Remove", 958206052)) );
					}
					
					
					case 770176554:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Edit", 770176554)) );
					}
					
					
					case 3254785:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "Add", 3254785)) );
					}
					
					
					case 4899648:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return this.bus;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
				switch (hash) {
					case 1835582091:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return this.FindById(global::haxe.lang.Runtime.toString(dynargs[0]));
					}
					
					
					case 958206052:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.Remove(global::haxe.lang.Runtime.toString(dynargs[0]));
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						break;
					}
					
					
					case 770176554:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.Edit(((global::englishauction.AuctionModel) (dynargs[0]) ));
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						break;
					}
					
					
					case 3254785:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						this.Add(((global::englishauction.AuctionModel) (dynargs[0]) ));
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						break;
					}
					
					
					default:
					{
						#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
			baseArr.push("bus");
			#line 5 "/my-component/src/englishauction/AuctionRepository.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


