// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class BidModel : global::haxe.lang.HxObject {
		
		public BidModel(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public BidModel() {
			#line 5 "/my-component/src/englishauction/BidModel.hx"
			global::englishauction.BidModel.__hx_ctor_englishauction_BidModel(this);
		}
		#line default
		
		protected static void __hx_ctor_englishauction_BidModel(global::englishauction.BidModel __hx_this) {
		}
		
		
		public string id;
		
		public string auctionId;
		
		public string userId;
		
		public double amount;
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/englishauction/BidModel.hx"
				switch (hash) {
					case 1426264536:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						this.amount = ((double) (@value) );
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return @value;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/englishauction/BidModel.hx"
				switch (hash) {
					case 1426264536:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						this.amount = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return @value;
					}
					
					
					case 1106197254:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						this.userId = global::haxe.lang.Runtime.toString(@value);
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return @value;
					}
					
					
					case 1182730494:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						this.auctionId = global::haxe.lang.Runtime.toString(@value);
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return @value;
					}
					
					
					case 23515:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						this.id = global::haxe.lang.Runtime.toString(@value);
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return @value;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/englishauction/BidModel.hx"
				switch (hash) {
					case 1426264536:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return this.amount;
					}
					
					
					case 1106197254:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return this.userId;
					}
					
					
					case 1182730494:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return this.auctionId;
					}
					
					
					case 23515:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return this.id;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				#line 3 "/my-component/src/englishauction/BidModel.hx"
				switch (hash) {
					case 1426264536:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return this.amount;
					}
					
					
					default:
					{
						#line 3 "/my-component/src/englishauction/BidModel.hx"
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 3 "/my-component/src/englishauction/BidModel.hx"
			baseArr.push("amount");
			#line 3 "/my-component/src/englishauction/BidModel.hx"
			baseArr.push("userId");
			#line 3 "/my-component/src/englishauction/BidModel.hx"
			baseArr.push("auctionId");
			#line 3 "/my-component/src/englishauction/BidModel.hx"
			baseArr.push("id");
			#line 3 "/my-component/src/englishauction/BidModel.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}


