// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction : global::haxe.lang.HxObject {
		
		static EnglishAuction() {
			unchecked{
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5541879, 13816588, 211137674, 263824376, 407283053, 907774356, 957002115, 1224901875}, new string[]{"obj", "SuppressWarnings", "auctionModelToMagLevObject", "convertToMagLev", "hasNext", "convertToHaxe", "registerMyMethods", "next"});
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				{
					#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::Array<object>(new object[]{new global::Array<object>(new object[]{"checkstyle:FieldDocComment", "checkstyle:LocalVariableName", "checkstyle:MultipleStringLiterals", "checkstyle:MagicNumber"})})}, new int[]{}, new double[]{});
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						global::englishauction.EnglishAuction.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
					}
					
				}
				
			}
		}
		#line default
		
		public EnglishAuction(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public EnglishAuction(global::maglev.MagLev maglev) {
			#line 16 "/my-component/src/englishauction/EnglishAuction.hx"
			global::englishauction.EnglishAuction.__hx_ctor_englishauction_EnglishAuction(this, maglev);
		}
		#line default
		
		protected static void __hx_ctor_englishauction_EnglishAuction(global::englishauction.EnglishAuction __hx_this, global::maglev.MagLev maglev) {
			#line 17 "/my-component/src/englishauction/EnglishAuction.hx"
			__hx_this.maglev = maglev;
			__hx_this.auctionRepo = new global::englishauction.AuctionRepository(((global::maglev.MagLev) (maglev) ));
			#line 19 "/my-component/src/englishauction/EnglishAuction.hx"
			__hx_this.bidRepo = new global::englishauction.BidRepository(((global::maglev.MagLev) (maglev) ));
			__hx_this.registerMyMethods();
		}
		#line default
		
		public static object __meta__;
		
		public global::maglev.MagLev maglev;
		
		public global::englishauction.AuctionRepository auctionRepo;
		
		public global::englishauction.BidRepository bidRepo;
		
		public virtual void registerMyMethods() {
			#line 23 "/my-component/src/englishauction/EnglishAuction.hx"
			global::englishauction.EnglishAuction _gthis = this;
			global::maglev.MagLev bus = this.maglev;
			#line 25 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.Create", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_25__Fun(_gthis)));
			#line 52 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetStart", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_52__Fun(bus)));
			#line 75 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetEnd", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_75__Fun(bus)));
			#line 98 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.HasStarted", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_98__Fun(bus)));
			#line 122 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.HasEnded", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_122__Fun(bus)));
			#line 146 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.Bid", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_146__Fun(bus)));
			#line 161 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetHighestBidder", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_161__Fun(bus)));
			#line 190 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetHighestBids", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_190__Fun(bus)));
			#line 222 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetNumberOfBids", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_222__Fun(_gthis)));
			#line 227 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetPriceIncrement", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_227__Fun(_gthis)));
			#line 238 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetPriceIncrement", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_238__Fun(_gthis)));
			#line 249 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetReservePrice", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_249__Fun(_gthis)));
			#line 260 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetStartingPrice", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_260__Fun(_gthis)));
			#line 271 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetMinimumBid", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_271__Fun(_gthis)));
			#line 282 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetTimeRemaining", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_282__Fun(_gthis)));
			#line 302 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetAuctionsEnding", global::maglev.MagLevFunction.fromFunction(new global::englishauction.EnglishAuction_registerMyMethods_302__Fun(_gthis)));
			#line 325 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetAuctionsStarting", global::maglev.MagLevFunction.fromFunction(( (( global::englishauction.EnglishAuction_registerMyMethods_325__Fun.__hx_current != null )) ? (global::englishauction.EnglishAuction_registerMyMethods_325__Fun.__hx_current) : (global::englishauction.EnglishAuction_registerMyMethods_325__Fun.__hx_current = ((global::englishauction.EnglishAuction_registerMyMethods_325__Fun) (new global::englishauction.EnglishAuction_registerMyMethods_325__Fun()) )) )));
			#line 330 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.GetOpenAuctions", global::maglev.MagLevFunction.fromFunction(( (( global::englishauction.EnglishAuction_registerMyMethods_330__Fun.__hx_current != null )) ? (global::englishauction.EnglishAuction_registerMyMethods_330__Fun.__hx_current) : (global::englishauction.EnglishAuction_registerMyMethods_330__Fun.__hx_current = ((global::englishauction.EnglishAuction_registerMyMethods_330__Fun) (new global::englishauction.EnglishAuction_registerMyMethods_330__Fun()) )) )));
		}
		#line default
		
		public virtual global::maglev.MagLevObject auctionModelToMagLevObject(global::englishauction.AuctionModel m) {
			#line 344 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevObject o = global::maglev.MagLevObject.create();
			o.@set("auctionId", global::maglev.MagLevString.fromString(m.id));
			#line 346 "/my-component/src/englishauction/EnglishAuction.hx"
			o.@set("start", global::maglev.MagLevNumber.fromInt(m.start));
			o.@set("end", global::maglev.MagLevNumber.fromInt(m.end));
			#line 348 "/my-component/src/englishauction/EnglishAuction.hx"
			o.@set("startingPrice", global::maglev.MagLevNumber.fromFloat(m.startingPrice));
			o.@set("reservePrice", global::maglev.MagLevNumber.fromFloat(m.reservePrice));
			#line 350 "/my-component/src/englishauction/EnglishAuction.hx"
			o.@set("priceIncrement", global::maglev.MagLevNumber.fromFloat(m.priceIncrement));
			return o;
		}
		#line default
		
		public virtual object convertToHaxe(global::maglev.MagLevAny x) {
			#line 355 "/my-component/src/englishauction/EnglishAuction.hx"
			if (( x.getType() == global::maglev.MagLevNull.getStaticType() )) {
				#line 356 "/my-component/src/englishauction/EnglishAuction.hx"
				return null;
			}
			else if (( x.getType() == global::maglev.MagLevBoolean.getStaticType() )) {
				#line 359 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevBoolean y = ((global::maglev.MagLevBoolean) (x) );
				return ((object) (y.getBool()) );
			}
			else if (( x.getType() == global::maglev.MagLevString.getStaticType() )) {
				#line 363 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevString y1 = ((global::maglev.MagLevString) (x) );
				return ((object) (y1.getString()) );
			}
			else if (( x.getType() == global::maglev.MagLevNumber.getStaticType() )) {
				#line 367 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevNumber y2 = ((global::maglev.MagLevNumber) (x) );
				return ((object) (y2.getFloat()) );
			}
			else if (( x.getType() == global::maglev.MagLevArray.getStaticType() )) {
				#line 371 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray y3 = ((global::maglev.MagLevArray) (x) );
				global::Array<object> arr = new global::Array<object>();
				#line 373 "/my-component/src/englishauction/EnglishAuction.hx"
				int i = 0;
				while (( i < y3.size() )) {
					#line 375 "/my-component/src/englishauction/EnglishAuction.hx"
					arr.push(this.convertToHaxe(y3.@get(i)));
				}
				
				#line 377 "/my-component/src/englishauction/EnglishAuction.hx"
				return ((object) (arr) );
			}
			else if (( x.getType() == global::maglev.MagLevObject.getStaticType() )) {
				#line 380 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevObject y4 = ((global::maglev.MagLevObject) (x) );
				global::haxe.ds.StringMap<object> map = new global::haxe.ds.StringMap<object>();
				#line 382 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray keys = y4.keys();
				int i1 = 0;
				#line 384 "/my-component/src/englishauction/EnglishAuction.hx"
				while (( i1 < keys.size() )) {
					#line 385 "/my-component/src/englishauction/EnglishAuction.hx"
					string key = (((global::maglev.MagLevString) (keys.@get(i1)) )).getString();
					map.@set(key, this.convertToHaxe(y4.@get(key)));
				}
				
				#line 388 "/my-component/src/englishauction/EnglishAuction.hx"
				return ((object) (map) );
			}
			else {
				#line 391 "/my-component/src/englishauction/EnglishAuction.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("convertToHaxe: unknown type")) );
			}
			
		}
		#line default
		
		public virtual global::maglev.MagLevAny convertToMagLev(object x) {
			#line 396 "/my-component/src/englishauction/EnglishAuction.hx"
			if (( x == null )) {
				#line 397 "/my-component/src/englishauction/EnglishAuction.hx"
				return global::maglev.MagLevNull.create();
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(bool)) ))) {
				#line 400 "/my-component/src/englishauction/EnglishAuction.hx"
				return global::maglev.MagLevBoolean.fromBool(global::haxe.lang.Runtime.toBool(x));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(string)) ))) {
				#line 403 "/my-component/src/englishauction/EnglishAuction.hx"
				return global::maglev.MagLevString.fromString(global::haxe.lang.Runtime.toString(x));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(int)) ))) {
				#line 406 "/my-component/src/englishauction/EnglishAuction.hx"
				return global::maglev.MagLevNumber.fromInt(((int) (global::haxe.lang.Runtime.toInt(x)) ));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(double)) ))) {
				#line 409 "/my-component/src/englishauction/EnglishAuction.hx"
				return global::maglev.MagLevNumber.fromFloat(((double) (global::haxe.lang.Runtime.toDouble(((object) (x) ))) ));
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(global::Array<object>)) ))) {
				#line 412 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray arr = global::maglev.MagLevArray.create();
				global::Array<object> y = ((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (((object) (x) )) ))) );
				#line 414 "/my-component/src/englishauction/EnglishAuction.hx"
				{
					#line 414 "/my-component/src/englishauction/EnglishAuction.hx"
					int _g = 0;
					#line 414 "/my-component/src/englishauction/EnglishAuction.hx"
					while (( _g < y.length )) {
						#line 414 "/my-component/src/englishauction/EnglishAuction.hx"
						object item = y[_g];
						#line 414 "/my-component/src/englishauction/EnglishAuction.hx"
						 ++ _g;
						arr.push(this.convertToMagLev(item));
					}
					
				}
				
				#line 417 "/my-component/src/englishauction/EnglishAuction.hx"
				return arr;
			}
			else if (global::Std.isOfType(((object) (x) ), ((object) (typeof(global::haxe.ds.StringMap<object>)) ))) {
				#line 420 "/my-component/src/englishauction/EnglishAuction.hx"
				global::haxe.ds.StringMap<object> map = ((global::haxe.ds.StringMap<object>) (global::haxe.ds.StringMap<object>.__hx_cast<object>(((global::haxe.ds.StringMap) (((object) (x) )) ))) );
				global::maglev.MagLevObject obj = global::maglev.MagLevObject.create();
				#line 422 "/my-component/src/englishauction/EnglishAuction.hx"
				{
					#line 422 "/my-component/src/englishauction/EnglishAuction.hx"
					object key = ((object) (new global::haxe.ds._StringMap.StringMapKeyIterator<object>(((global::haxe.ds.StringMap<object>) (map) ))) );
					#line 422 "/my-component/src/englishauction/EnglishAuction.hx"
					while (global::haxe.lang.Runtime.toBool(global::haxe.lang.Runtime.callField(key, "hasNext", 407283053, null))) {
						#line 422 "/my-component/src/englishauction/EnglishAuction.hx"
						string key1 = global::haxe.lang.Runtime.toString(global::haxe.lang.Runtime.callField(key, "next", 1224901875, null));
						obj.@set(key1, this.convertToMagLev((map.@get(key1)).toDynamic()));
					}
					
				}
				
				#line 425 "/my-component/src/englishauction/EnglishAuction.hx"
				return obj;
			}
			else if (global::Reflect.isObject(x)) {
				#line 428 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevObject obj1 = global::maglev.MagLevObject.create();
				{
					#line 429 "/my-component/src/englishauction/EnglishAuction.hx"
					int _g1 = 0;
					#line 429 "/my-component/src/englishauction/EnglishAuction.hx"
					global::Array<string> _g2 = global::Reflect.fields(x);
					#line 429 "/my-component/src/englishauction/EnglishAuction.hx"
					while (( _g1 < _g2.length )) {
						#line 429 "/my-component/src/englishauction/EnglishAuction.hx"
						string field = _g2[_g1];
						#line 429 "/my-component/src/englishauction/EnglishAuction.hx"
						 ++ _g1;
						object val = global::Reflect.getProperty(x, field);
						#line 431 "/my-component/src/englishauction/EnglishAuction.hx"
						obj1.@set(field, this.convertToMagLev(val));
					}
					
				}
				
				#line 433 "/my-component/src/englishauction/EnglishAuction.hx"
				return obj1;
			}
			else if (( ((object) (x) ) is global::haxe.lang.Function )) {
				#line 436 "/my-component/src/englishauction/EnglishAuction.hx"
				global::haxe.lang.Function f = ((global::haxe.lang.Function) (((object) (x) )) );
				return global::maglev.MagLevFunction.fromFunction(f);
			}
			else {
				#line 440 "/my-component/src/englishauction/EnglishAuction.hx"
				throw ((global::System.Exception) (global::haxe.Exception.thrown("convertToMagLev: unknown type")) );
			}
			
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				switch (hash) {
					case 826466255:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						this.bidRepo = ((global::englishauction.BidRepository) (@value) );
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return @value;
					}
					
					
					case 822465621:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						this.auctionRepo = ((global::englishauction.AuctionRepository) (@value) );
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return @value;
					}
					
					
					case 858513194:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						this.maglev = ((global::maglev.MagLev) (@value) );
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return @value;
					}
					
					
					default:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				switch (hash) {
					case 263824376:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "convertToMagLev", 263824376)) );
					}
					
					
					case 907774356:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "convertToHaxe", 907774356)) );
					}
					
					
					case 211137674:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "auctionModelToMagLevObject", 211137674)) );
					}
					
					
					case 957002115:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "registerMyMethods", 957002115)) );
					}
					
					
					case 826466255:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return this.bidRepo;
					}
					
					
					case 822465621:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return this.auctionRepo;
					}
					
					
					case 858513194:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return this.maglev;
					}
					
					
					default:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				switch (hash) {
					case 263824376:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return this.convertToMagLev(dynargs[0]);
					}
					
					
					case 907774356:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return this.convertToHaxe(((global::maglev.MagLevAny) (dynargs[0]) ));
					}
					
					
					case 211137674:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return this.auctionModelToMagLevObject(((global::englishauction.AuctionModel) (dynargs[0]) ));
					}
					
					
					case 957002115:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						this.registerMyMethods();
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						break;
					}
					
					
					default:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
			baseArr.push("bidRepo");
			#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
			baseArr.push("auctionRepo");
			#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
			baseArr.push("maglev");
			#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_25__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_25__Fun(global::englishauction.EnglishAuction _gthis) : base(1, 0) {
			#line 25 "/my-component/src/englishauction/EnglishAuction.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 25 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				#line 27 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevNumber start = ((global::maglev.MagLevNumber) (args.@get(0)) );
				global::maglev.MagLevNumber end = ((global::maglev.MagLevNumber) (args.@get(1)) );
				#line 29 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevNumber startingPrice = ((global::maglev.MagLevNumber) (args.@get(2)) );
				global::maglev.MagLevNumber reservePrice = ((global::maglev.MagLevNumber) (args.@get(3)) );
				#line 31 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevNumber priceIncrement = ((global::maglev.MagLevNumber) (args.@get(4)) );
				global::maglev.MagLevObject obj = global::maglev.MagLevObject.create();
				#line 33 "/my-component/src/englishauction/EnglishAuction.hx"
				obj.@set("start", start);
				obj.@set("end", end);
				#line 35 "/my-component/src/englishauction/EnglishAuction.hx"
				obj.@set("startingPrice", startingPrice);
				obj.@set("reservePrice", reservePrice);
				#line 37 "/my-component/src/englishauction/EnglishAuction.hx"
				obj.@set("priceIncrement", priceIncrement);
				global::maglev.MagLevArray myargs = global::maglev.MagLevArray.create();
				#line 39 "/my-component/src/englishauction/EnglishAuction.hx"
				myargs.push(global::maglev.MagLevString.fromString("EnglishAuction.Auction"));
				myargs.push(global::maglev.MagLevString.fromString("CreateNew"));
				#line 41 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray myarr = global::maglev.MagLevArray.create();
				myarr.push(obj);
				#line 43 "/my-component/src/englishauction/EnglishAuction.hx"
				myargs.push(obj);
				this._gthis.maglev.call("Persistence.Mutate", myargs);
				#line 45 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray myargs2 = global::maglev.MagLevArray.create();
				myargs2.push(global::maglev.MagLevString.fromString("EnglishAuction.Auction"));
				#line 47 "/my-component/src/englishauction/EnglishAuction.hx"
				myargs2.push(global::maglev.MagLevString.fromString("NewAuctionId"));
				myargs2.push(global::maglev.MagLevArray.create());
				#line 49 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevResult res = this._gthis.maglev.call("Persistence.Get", myargs2);
				return res;
			}
			#line default
		}
		
		
		public global::englishauction.EnglishAuction _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_52__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_52__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 52 "/my-component/src/englishauction/EnglishAuction.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 52 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			global::maglev.MagLevString id = ((global::maglev.MagLevString) (args.@get(0)) );
			#line 54 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray myargs = global::maglev.MagLevArray.create();
			myargs.push(global::maglev.MagLevString.fromString("EnglishAuction.Auction"));
			#line 56 "/my-component/src/englishauction/EnglishAuction.hx"
			myargs.push(global::maglev.MagLevString.fromString("FindById"));
			myargs.push(id);
			#line 58 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevResult res = this.bus.call("Persistence.Get", myargs);
			if (res.isError()) {
				#line 59 "/my-component/src/englishauction/EnglishAuction.hx"
				return res;
			}
			
			#line 60 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevObject resobj = ((global::maglev.MagLevObject) (res.getResult()) );
			double start = ((double) (0) );
			#line 62 "/my-component/src/englishauction/EnglishAuction.hx"
			if (global::Std.isOfType(((object) (resobj.@get("start")) ), ((object) (typeof(global::maglev.MagLevString)) ))) {
				#line 63 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevString y = ((global::maglev.MagLevString) (resobj.@get("start")) );
				global::Date _this = global::Date.fromString(y.getString());
				start = ( ((double) (((long) (( ((long) (global::System.TimeZone.CurrentTimeZone.ToUniversalTime(((global::System.DateTime) (_this.date) )).Ticks) ) - ((long) (global::Date.epochTicks) ) )) )) ) / ((double) (global::System.TimeSpan.TicksPerMillisecond) ) );
			}
			else if (global::Std.isOfType(((object) (resobj.@get("start")) ), ((object) (typeof(global::maglev.MagLevNumber)) ))) {
				#line 66 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevNumber y1 = ((global::maglev.MagLevNumber) (resobj.@get("start")) );
				start = y1.getFloat();
			}
			else {
				#line 69 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "persistence getter did not return object with start as number or string", global::maglev.MagLevNull.create());
				return global::maglev.MagLevResult.fromError(error);
			}
			
			#line 72 "/my-component/src/englishauction/EnglishAuction.hx"
			double result = start;
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNumber.fromFloat(result));
		}
		#line default
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_75__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_75__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 75 "/my-component/src/englishauction/EnglishAuction.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 75 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			global::maglev.MagLevString id = ((global::maglev.MagLevString) (args.@get(0)) );
			#line 77 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray myargs = global::maglev.MagLevArray.create();
			myargs.push(global::maglev.MagLevString.fromString("EnglishAuction.Auction"));
			#line 79 "/my-component/src/englishauction/EnglishAuction.hx"
			myargs.push(global::maglev.MagLevString.fromString("FindById"));
			myargs.push(id);
			#line 81 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevResult res = this.bus.call("Persistence.Get", myargs);
			if (res.isError()) {
				#line 82 "/my-component/src/englishauction/EnglishAuction.hx"
				return res;
			}
			
			#line 83 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevObject resobj = ((global::maglev.MagLevObject) (res.getResult()) );
			double end = ((double) (0) );
			#line 85 "/my-component/src/englishauction/EnglishAuction.hx"
			if (global::Std.isOfType(((object) (resobj.@get("end")) ), ((object) (typeof(global::maglev.MagLevString)) ))) {
				#line 86 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevString y = ((global::maglev.MagLevString) (resobj.@get("end")) );
				global::Date _this = global::Date.fromString(y.getString());
				end = ( ((double) (((long) (( ((long) (global::System.TimeZone.CurrentTimeZone.ToUniversalTime(((global::System.DateTime) (_this.date) )).Ticks) ) - ((long) (global::Date.epochTicks) ) )) )) ) / ((double) (global::System.TimeSpan.TicksPerMillisecond) ) );
			}
			else if (global::Std.isOfType(((object) (resobj.@get("end")) ), ((object) (typeof(global::maglev.MagLevNumber)) ))) {
				#line 89 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevNumber y1 = ((global::maglev.MagLevNumber) (resobj.@get("end")) );
				end = y1.getFloat();
			}
			else {
				#line 92 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "persistence getter did not return object with end as number or string", global::maglev.MagLevNull.create());
				return global::maglev.MagLevResult.fromError(error);
			}
			
			#line 95 "/my-component/src/englishauction/EnglishAuction.hx"
			double result = end;
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNumber.fromFloat(result));
		}
		#line default
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_98__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_98__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 98 "/my-component/src/englishauction/EnglishAuction.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 98 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			global::maglev.MagLevString id = ((global::maglev.MagLevString) (args.@get(0)) );
			#line 100 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray myargs = global::maglev.MagLevArray.create();
			myargs.push(global::maglev.MagLevString.fromString("EnglishAuction.Auction"));
			#line 102 "/my-component/src/englishauction/EnglishAuction.hx"
			myargs.push(global::maglev.MagLevString.fromString("FindById"));
			myargs.push(id);
			#line 104 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevResult res = this.bus.call("Persistence.Get", myargs);
			if (res.isError()) {
				#line 105 "/my-component/src/englishauction/EnglishAuction.hx"
				return res;
			}
			
			#line 106 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevObject resobj = ((global::maglev.MagLevObject) (res.getResult()) );
			double start = ((double) (0) );
			#line 108 "/my-component/src/englishauction/EnglishAuction.hx"
			if (global::Std.isOfType(((object) (resobj.@get("start")) ), ((object) (typeof(global::maglev.MagLevString)) ))) {
				#line 109 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevString y = ((global::maglev.MagLevString) (resobj.@get("start")) );
				global::Date _this = global::Date.fromString(y.getString());
				start = ( ((double) (((long) (( ((long) (global::System.TimeZone.CurrentTimeZone.ToUniversalTime(((global::System.DateTime) (_this.date) )).Ticks) ) - ((long) (global::Date.epochTicks) ) )) )) ) / ((double) (global::System.TimeSpan.TicksPerMillisecond) ) );
			}
			else if (global::Std.isOfType(((object) (resobj.@get("start")) ), ((object) (typeof(global::maglev.MagLevNumber)) ))) {
				#line 112 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevNumber y1 = ((global::maglev.MagLevNumber) (resobj.@get("start")) );
				start = y1.getFloat();
			}
			else {
				#line 115 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "persistence getter did not return object with start as number or string", global::maglev.MagLevNull.create());
				return global::maglev.MagLevResult.fromError(error);
			}
			
			#line 118 "/my-component/src/englishauction/EnglishAuction.hx"
			global::Date _this1 = new global::Date(((global::System.DateTime) (global::System.DateTime.Now) ));
			#line 118 "/my-component/src/englishauction/EnglishAuction.hx"
			double now = ( ((double) (((long) (( ((long) (global::System.TimeZone.CurrentTimeZone.ToUniversalTime(((global::System.DateTime) (_this1.date) )).Ticks) ) - ((long) (global::Date.epochTicks) ) )) )) ) / ((double) (global::System.TimeSpan.TicksPerMillisecond) ) );
			bool result = ( start <= now );
			#line 120 "/my-component/src/englishauction/EnglishAuction.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevBoolean.fromBool(result));
		}
		#line default
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_122__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_122__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 122 "/my-component/src/englishauction/EnglishAuction.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 122 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			global::maglev.MagLevString id = ((global::maglev.MagLevString) (args.@get(0)) );
			#line 124 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray myargs = global::maglev.MagLevArray.create();
			myargs.push(global::maglev.MagLevString.fromString("EnglishAuction.Auction"));
			#line 126 "/my-component/src/englishauction/EnglishAuction.hx"
			myargs.push(global::maglev.MagLevString.fromString("FindById"));
			myargs.push(id);
			#line 128 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevResult res = this.bus.call("Persistence.Get", myargs);
			if (res.isError()) {
				#line 129 "/my-component/src/englishauction/EnglishAuction.hx"
				return res;
			}
			
			#line 130 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevObject resobj = ((global::maglev.MagLevObject) (res.getResult()) );
			double end = ((double) (0) );
			#line 132 "/my-component/src/englishauction/EnglishAuction.hx"
			if (global::Std.isOfType(((object) (resobj.@get("end")) ), ((object) (typeof(global::maglev.MagLevString)) ))) {
				#line 133 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevString y = ((global::maglev.MagLevString) (resobj.@get("end")) );
				global::Date _this = global::Date.fromString(y.getString());
				end = ( ((double) (((long) (( ((long) (global::System.TimeZone.CurrentTimeZone.ToUniversalTime(((global::System.DateTime) (_this.date) )).Ticks) ) - ((long) (global::Date.epochTicks) ) )) )) ) / ((double) (global::System.TimeSpan.TicksPerMillisecond) ) );
			}
			else if (global::Std.isOfType(((object) (resobj.@get("end")) ), ((object) (typeof(global::maglev.MagLevNumber)) ))) {
				#line 136 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevNumber y1 = ((global::maglev.MagLevNumber) (resobj.@get("end")) );
				end = y1.getFloat();
			}
			else {
				#line 139 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "persistence getter did not return object with end as number or string", global::maglev.MagLevNull.create());
				return global::maglev.MagLevResult.fromError(error);
			}
			
			#line 142 "/my-component/src/englishauction/EnglishAuction.hx"
			global::Date _this1 = new global::Date(((global::System.DateTime) (global::System.DateTime.Now) ));
			#line 142 "/my-component/src/englishauction/EnglishAuction.hx"
			double now = ( ((double) (((long) (( ((long) (global::System.TimeZone.CurrentTimeZone.ToUniversalTime(((global::System.DateTime) (_this1.date) )).Ticks) ) - ((long) (global::Date.epochTicks) ) )) )) ) / ((double) (global::System.TimeSpan.TicksPerMillisecond) ) );
			bool result = ( now > end );
			#line 144 "/my-component/src/englishauction/EnglishAuction.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevBoolean.fromBool(result));
		}
		#line default
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_146__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_146__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 146 "/my-component/src/englishauction/EnglishAuction.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 146 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevString auctionId = ((global::maglev.MagLevString) (args.@get(0)) );
				#line 148 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevString userId = ((global::maglev.MagLevString) (args.@get(1)) );
				global::maglev.MagLevNumber price = ((global::maglev.MagLevNumber) (args.@get(2)) );
				#line 150 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevObject data = global::maglev.MagLevObject.create();
				data.@set("auctionId", auctionId);
				#line 152 "/my-component/src/englishauction/EnglishAuction.hx"
				data.@set("userId", userId);
				data.@set("price", price);
				#line 154 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray args1 = global::maglev.MagLevArray.create();
				args1.push(global::maglev.MagLevString.fromString("EnglishAuction.Bid"));
				#line 156 "/my-component/src/englishauction/EnglishAuction.hx"
				args1.push(global::maglev.MagLevString.fromString("New"));
				args1.push(data);
				#line 158 "/my-component/src/englishauction/EnglishAuction.hx"
				this.bus.call("Persistence.Mutate", args1);
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevBoolean.fromBool(true));
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_161__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_161__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 161 "/my-component/src/englishauction/EnglishAuction.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 161 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevString auctionId = ((global::maglev.MagLevString) (args.@get(0)) );
				#line 163 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray myargs = global::maglev.MagLevArray.create();
				myargs.push(auctionId);
				#line 165 "/my-component/src/englishauction/EnglishAuction.hx"
				myargs.push(global::maglev.MagLevNumber.fromInt(1));
				global::maglev.MagLevArray myargs2 = global::maglev.MagLevArray.create();
				#line 167 "/my-component/src/englishauction/EnglishAuction.hx"
				myargs2.push(global::maglev.MagLevString.fromString("EnglishAuction.Bid"));
				myargs2.push(global::maglev.MagLevString.fromString("FindByHighestPriceForAuction"));
				#line 169 "/my-component/src/englishauction/EnglishAuction.hx"
				myargs2.push(myargs);
				global::maglev.MagLevResult ret = this.bus.call("Persistence.Get", myargs2);
				#line 171 "/my-component/src/englishauction/EnglishAuction.hx"
				if (ret.isError()) {
					#line 171 "/my-component/src/englishauction/EnglishAuction.hx"
					return ret;
				}
				
				#line 172 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevAny res = ret.getResult();
				if (global::Std.isOfType(((object) (res) ), ((object) (typeof(global::maglev.MagLevArray)) ))) {
					#line 174 "/my-component/src/englishauction/EnglishAuction.hx"
					global::maglev.MagLevArray resarr = ((global::maglev.MagLevArray) (res) );
					if (( resarr.size() > 0 )) {
						#line 176 "/my-component/src/englishauction/EnglishAuction.hx"
						global::maglev.MagLevObject row = ((global::maglev.MagLevObject) (resarr.@get(0)) );
						global::maglev.MagLevObject row2 = global::maglev.MagLevObject.create();
						#line 178 "/my-component/src/englishauction/EnglishAuction.hx"
						row2.@set("userId", row.@get("userId"));
						row2.@set("price", row.@get("price"));
						#line 180 "/my-component/src/englishauction/EnglishAuction.hx"
						return global::maglev.MagLevResult.fromResult(row2);
					}
					else {
						#line 182 "/my-component/src/englishauction/EnglishAuction.hx"
						return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
					}
					
				}
				else {
					#line 186 "/my-component/src/englishauction/EnglishAuction.hx"
					global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "persistence getter did not return array", global::maglev.MagLevNull.create());
					return global::maglev.MagLevResult.fromError(error);
				}
				
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_190__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_190__Fun(global::maglev.MagLev bus) : base(1, 0) {
			#line 190 "/my-component/src/englishauction/EnglishAuction.hx"
			this.bus = bus;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 190 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				global::maglev.MagLevString auctionId = ((global::maglev.MagLevString) (args.@get(0)) );
				#line 192 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevNumber numBids = ((global::maglev.MagLevNumber) (args.@get(1)) );
				global::maglev.MagLevArray myargs = global::maglev.MagLevArray.create();
				#line 194 "/my-component/src/englishauction/EnglishAuction.hx"
				myargs.push(auctionId);
				myargs.push(numBids);
				#line 196 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray myargs2 = global::maglev.MagLevArray.create();
				myargs2.push(global::maglev.MagLevString.fromString("EnglishAuction.Bid"));
				#line 198 "/my-component/src/englishauction/EnglishAuction.hx"
				myargs2.push(global::maglev.MagLevString.fromString("FindByHighestPriceForAuction"));
				myargs2.push(myargs);
				#line 200 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevResult ret = this.bus.call("Persistence.Get", myargs2);
				if (ret.isError()) {
					#line 201 "/my-component/src/englishauction/EnglishAuction.hx"
					return ret;
				}
				
				#line 202 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevAny res = ret.getResult();
				global::maglev.MagLevArray bids = global::maglev.MagLevArray.create();
				#line 204 "/my-component/src/englishauction/EnglishAuction.hx"
				if (global::Std.isOfType(((object) (res) ), ((object) (typeof(global::maglev.MagLevArray)) ))) {
					#line 205 "/my-component/src/englishauction/EnglishAuction.hx"
					global::maglev.MagLevArray resarr = ((global::maglev.MagLevArray) (res) );
					int i = 0;
					#line 207 "/my-component/src/englishauction/EnglishAuction.hx"
					while (( i < resarr.size() )) {
						#line 208 "/my-component/src/englishauction/EnglishAuction.hx"
						global::maglev.MagLevObject row = ((global::maglev.MagLevObject) (resarr.@get(i)) );
						global::maglev.MagLevObject row2 = global::maglev.MagLevObject.create();
						#line 210 "/my-component/src/englishauction/EnglishAuction.hx"
						row2.@set("userId", row.@get("userId"));
						row2.@set("price", row.@get("price"));
						#line 212 "/my-component/src/englishauction/EnglishAuction.hx"
						bids.push(row2);
						 ++ i;
					}
					
					#line 215 "/my-component/src/englishauction/EnglishAuction.hx"
					return global::maglev.MagLevResult.fromResult(bids);
				}
				else {
					#line 218 "/my-component/src/englishauction/EnglishAuction.hx"
					global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "persistence getter did not return array", global::maglev.MagLevNull.create());
					return global::maglev.MagLevResult.fromError(error);
				}
				
			}
			#line default
		}
		
		
		public global::maglev.MagLev bus;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_222__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_222__Fun(global::englishauction.EnglishAuction _gthis) : base(1, 0) {
			#line 222 "/my-component/src/englishauction/EnglishAuction.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 222 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			string auctionId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			#line 224 "/my-component/src/englishauction/EnglishAuction.hx"
			int numBids = this._gthis.bidRepo.GetNumberOfBids(auctionId);
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNumber.fromInt(numBids));
		}
		#line default
		
		public global::englishauction.EnglishAuction _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_227__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_227__Fun(global::englishauction.EnglishAuction _gthis) : base(1, 0) {
			#line 227 "/my-component/src/englishauction/EnglishAuction.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 227 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			string auctionId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			#line 229 "/my-component/src/englishauction/EnglishAuction.hx"
			global::englishauction.AuctionModel auction = this._gthis.auctionRepo.FindById(auctionId);
			if (( auction == null )) {
				#line 231 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "auction not found", global::maglev.MagLevNull.create());
				return global::maglev.MagLevResult.fromError(error);
			}
			else {
				#line 234 "/my-component/src/englishauction/EnglishAuction.hx"
				double priceIncrement = auction.priceIncrement;
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNumber.fromFloat(priceIncrement));
			}
			
		}
		#line default
		
		public global::englishauction.EnglishAuction _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_238__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_238__Fun(global::englishauction.EnglishAuction _gthis) : base(1, 0) {
			#line 238 "/my-component/src/englishauction/EnglishAuction.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 238 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			string auctionId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			#line 240 "/my-component/src/englishauction/EnglishAuction.hx"
			global::englishauction.AuctionModel auction = this._gthis.auctionRepo.FindById(auctionId);
			if (( auction == null )) {
				#line 242 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "auction not found", global::maglev.MagLevNull.create());
				return global::maglev.MagLevResult.fromError(error);
			}
			else {
				#line 245 "/my-component/src/englishauction/EnglishAuction.hx"
				double priceIncrement = auction.priceIncrement;
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNumber.fromFloat(priceIncrement));
			}
			
		}
		#line default
		
		public global::englishauction.EnglishAuction _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_249__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_249__Fun(global::englishauction.EnglishAuction _gthis) : base(1, 0) {
			#line 249 "/my-component/src/englishauction/EnglishAuction.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 249 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			string auctionId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			#line 251 "/my-component/src/englishauction/EnglishAuction.hx"
			global::englishauction.AuctionModel auction = this._gthis.auctionRepo.FindById(auctionId);
			if (( auction == null )) {
				#line 253 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "auction not found", global::maglev.MagLevNull.create());
				return global::maglev.MagLevResult.fromError(error);
			}
			else {
				#line 256 "/my-component/src/englishauction/EnglishAuction.hx"
				double reservePrice = auction.reservePrice;
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNumber.fromFloat(reservePrice));
			}
			
		}
		#line default
		
		public global::englishauction.EnglishAuction _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_260__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_260__Fun(global::englishauction.EnglishAuction _gthis) : base(1, 0) {
			#line 260 "/my-component/src/englishauction/EnglishAuction.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 260 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			string auctionId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			#line 262 "/my-component/src/englishauction/EnglishAuction.hx"
			global::englishauction.AuctionModel auction = this._gthis.auctionRepo.FindById(auctionId);
			if (( auction == null )) {
				#line 264 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "auction not found", global::maglev.MagLevNull.create());
				return global::maglev.MagLevResult.fromError(error);
			}
			else {
				#line 267 "/my-component/src/englishauction/EnglishAuction.hx"
				double startingPrice = auction.startingPrice;
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNumber.fromFloat(startingPrice));
			}
			
		}
		#line default
		
		public global::englishauction.EnglishAuction _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_271__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_271__Fun(global::englishauction.EnglishAuction _gthis) : base(1, 0) {
			#line 271 "/my-component/src/englishauction/EnglishAuction.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 271 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			string auctionId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
			#line 273 "/my-component/src/englishauction/EnglishAuction.hx"
			global::englishauction.AuctionModel auction = this._gthis.auctionRepo.FindById(auctionId);
			if (( auction == null )) {
				#line 275 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "auction not found", global::maglev.MagLevNull.create());
				return global::maglev.MagLevResult.fromError(error);
			}
			else {
				#line 279 "/my-component/src/englishauction/EnglishAuction.hx"
				return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
			}
			
		}
		#line default
		
		public global::englishauction.EnglishAuction _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_282__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_282__Fun(global::englishauction.EnglishAuction _gthis) : base(1, 0) {
			#line 282 "/my-component/src/englishauction/EnglishAuction.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 282 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				string auctionId = (((global::maglev.MagLevString) (args.@get(0)) )).getString();
				#line 284 "/my-component/src/englishauction/EnglishAuction.hx"
				global::Date _this = new global::Date(((global::System.DateTime) (global::System.DateTime.Now) ));
				#line 284 "/my-component/src/englishauction/EnglishAuction.hx"
				int now = ((int) (( ((double) (((long) (( ((long) (global::System.TimeZone.CurrentTimeZone.ToUniversalTime(((global::System.DateTime) (_this.date) )).Ticks) ) - ((long) (global::Date.epochTicks) ) )) )) ) / ((double) (global::System.TimeSpan.TicksPerMillisecond) ) )) );
				if (( args.size() > 1 )) {
					#line 286 "/my-component/src/englishauction/EnglishAuction.hx"
					now = (((global::maglev.MagLevNumber) (args.@get(1)) )).getInt();
				}
				
				#line 288 "/my-component/src/englishauction/EnglishAuction.hx"
				global::englishauction.AuctionModel auction = this._gthis.auctionRepo.FindById(auctionId);
				if (( auction == null )) {
					#line 290 "/my-component/src/englishauction/EnglishAuction.hx"
					global::maglev.MagLevError error = global::maglev.MagLevError.create(0, "auction not found", global::maglev.MagLevNull.create());
					return global::maglev.MagLevResult.fromError(error);
				}
				else {
					#line 293 "/my-component/src/englishauction/EnglishAuction.hx"
					int timeRemaining = ( auction.end - now );
					if (( timeRemaining < 0 )) {
						#line 295 "/my-component/src/englishauction/EnglishAuction.hx"
						timeRemaining = 0;
					}
					
					#line 297 "/my-component/src/englishauction/EnglishAuction.hx"
					return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNumber.fromInt(timeRemaining));
				}
				
			}
			#line default
		}
		
		
		public global::englishauction.EnglishAuction _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_302__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_302__Fun(global::englishauction.EnglishAuction _gthis) : base(1, 0) {
			#line 302 "/my-component/src/englishauction/EnglishAuction.hx"
			this._gthis = _gthis;
		}
		#line default
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			unchecked {
				#line 302 "/my-component/src/englishauction/EnglishAuction.hx"
				global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
				int endfrom = (((global::maglev.MagLevNumber) (args.@get(0)) )).getInt();
				#line 304 "/my-component/src/englishauction/EnglishAuction.hx"
				int endto = (((global::maglev.MagLevNumber) (args.@get(1)) )).getInt();
				int page = (((global::maglev.MagLevNumber) (args.@get(2)) )).getInt();
				#line 306 "/my-component/src/englishauction/EnglishAuction.hx"
				int perpage = (((global::maglev.MagLevNumber) (args.@get(3)) )).getInt();
				string sort = "end";
				#line 308 "/my-component/src/englishauction/EnglishAuction.hx"
				bool asc = true;
				if (( args.size() > 4 )) {
					#line 310 "/my-component/src/englishauction/EnglishAuction.hx"
					sort = (((global::maglev.MagLevString) (args.@get(4)) )).getString();
				}
				
				#line 312 "/my-component/src/englishauction/EnglishAuction.hx"
				if (( args.size() > 5 )) {
					#line 313 "/my-component/src/englishauction/EnglishAuction.hx"
					asc = (((global::maglev.MagLevBoolean) (args.@get(4)) )).getBool();
				}
				
				#line 315 "/my-component/src/englishauction/EnglishAuction.hx"
				global::Array<object> auctions = this._gthis.auctionRepo.FindAuctionsEnding(endfrom, endto, page, perpage, sort, asc);
				global::maglev.MagLevArray results = global::maglev.MagLevArray.create();
				#line 317 "/my-component/src/englishauction/EnglishAuction.hx"
				{
					#line 317 "/my-component/src/englishauction/EnglishAuction.hx"
					int _g = 0;
					#line 317 "/my-component/src/englishauction/EnglishAuction.hx"
					while (( _g < auctions.length )) {
						#line 317 "/my-component/src/englishauction/EnglishAuction.hx"
						global::englishauction.AuctionModel auction = ((global::englishauction.AuctionModel) (auctions[_g]) );
						#line 317 "/my-component/src/englishauction/EnglishAuction.hx"
						 ++ _g;
						global::maglev.MagLevObject result = this._gthis.auctionModelToMagLevObject(auction);
						#line 319 "/my-component/src/englishauction/EnglishAuction.hx"
						results.push(result);
					}
					
				}
				
				#line 321 "/my-component/src/englishauction/EnglishAuction.hx"
				return global::maglev.MagLevResult.fromResult(results);
			}
			#line default
		}
		
		
		public global::englishauction.EnglishAuction _gthis;
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_325__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_325__Fun() : base(1, 0) {
		}
		
		
		public static global::englishauction.EnglishAuction_registerMyMethods_325__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 325 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			#line 327 "/my-component/src/englishauction/EnglishAuction.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_330__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_330__Fun() : base(1, 0) {
		}
		
		
		public static global::englishauction.EnglishAuction_registerMyMethods_330__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 330 "/my-component/src/englishauction/EnglishAuction.hx"
			global::maglev.MagLevArray args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::maglev.MagLevArray) (((object) (__fn_float1) )) )) : (((global::maglev.MagLevArray) (__fn_dyn1) )) );
			#line 332 "/my-component/src/englishauction/EnglishAuction.hx"
			return global::maglev.MagLevResult.fromResult(global::maglev.MagLevNull.create());
		}
		#line default
		
	}
}


