// Generated by Haxe 4.1.1

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction : global::haxe.lang.HxObject {
		
		static EnglishAuction() {
			unchecked{
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				global::haxe.lang.FieldLookup.addFields(new int[]{5541879, 13816588, 957002115}, new string[]{"obj", "SuppressWarnings", "registerMyMethods"});
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				{
					#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						object __temp_odecl1 = new global::haxe.lang.DynamicObject(new int[]{13816588}, new object[]{new global::Array<object>(new object[]{new global::Array<object>(new object[]{"checkstyle:FieldDocComment", "checkstyle:LocalVariableName", "checkstyle:MultipleStringLiterals", "checkstyle:MagicNumber"})})}, new int[]{}, new double[]{});
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						global::englishauction.EnglishAuction.__meta__ = new global::haxe.lang.DynamicObject(new int[]{5541879}, new object[]{__temp_odecl1}, new int[]{}, new double[]{});
					}
					
				}
				
			}
		}
		#line default
		
		public EnglishAuction(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public EnglishAuction(global::maglev.MagLev maglev) {
			#line 14 "/my-component/src/englishauction/EnglishAuction.hx"
			global::englishauction.EnglishAuction.__hx_ctor_englishauction_EnglishAuction(this, maglev);
		}
		#line default
		
		protected static void __hx_ctor_englishauction_EnglishAuction(global::englishauction.EnglishAuction __hx_this, global::maglev.MagLev maglev) {
			#line 15 "/my-component/src/englishauction/EnglishAuction.hx"
			__hx_this.maglev = maglev;
			__hx_this.registerMyMethods();
		}
		#line default
		
		public static object __meta__;
		
		public global::maglev.MagLev maglev;
		
		public virtual void registerMyMethods() {
			#line 20 "/my-component/src/englishauction/EnglishAuction.hx"
			this.maglev.register("EnglishAuction.Create", ( (( global::englishauction.EnglishAuction_registerMyMethods_20__Fun.__hx_current != null )) ? (global::englishauction.EnglishAuction_registerMyMethods_20__Fun.__hx_current) : (global::englishauction.EnglishAuction_registerMyMethods_20__Fun.__hx_current = ((global::englishauction.EnglishAuction_registerMyMethods_20__Fun) (new global::englishauction.EnglishAuction_registerMyMethods_20__Fun()) )) ));
		}
		#line default
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				switch (hash) {
					case 858513194:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						this.maglev = ((global::maglev.MagLev) (@value) );
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return @value;
					}
					
					
					default:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				switch (hash) {
					case 957002115:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "registerMyMethods", 957002115)) );
					}
					
					
					case 858513194:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return this.maglev;
					}
					
					
					default:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
			#line default
		}
		
		
		public override object __hx_invokeField(string field, int hash, object[] dynargs) {
			unchecked {
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				switch (hash) {
					case 957002115:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						this.registerMyMethods();
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						break;
					}
					
					
					default:
					{
						#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
				#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
				return null;
			}
			#line default
		}
		
		
		public override void __hx_getFields(global::Array<string> baseArr) {
			#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
			baseArr.push("maglev");
			#line 11 "/my-component/src/englishauction/EnglishAuction.hx"
			base.__hx_getFields(baseArr);
		}
		#line default
		
	}
}



#pragma warning disable 109, 114, 219, 429, 168, 162
namespace englishauction {
	public class EnglishAuction_registerMyMethods_20__Fun : global::haxe.lang.Function {
		
		public EnglishAuction_registerMyMethods_20__Fun() : base(1, 0) {
		}
		
		
		public static global::englishauction.EnglishAuction_registerMyMethods_20__Fun __hx_current;
		
		public override object __hx_invoke1_o(double __fn_float1, object __fn_dyn1) {
			#line 20 "/my-component/src/englishauction/EnglishAuction.hx"
			global::Array<object> args = ( (( __fn_dyn1 == global::haxe.lang.Runtime.undefined )) ? (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (((object) (__fn_float1) )) ))) )) : (((global::Array<object>) (global::Array<object>.__hx_cast<object>(((global::Array) (__fn_dyn1) ))) )) );
			string ret = "idhere";
			#line 22 "/my-component/src/englishauction/EnglishAuction.hx"
			return ((object) (ret) );
		}
		#line default
		
	}
}


